### ISSUE TITLE
Move documentation to a doc directory.

### ISSUE THREAD

**Issue by hayesall** [starling-lab/BoostSRL#5]
# Overview

There are many files in the `code` directory which are not actually code, including documentation, TeX, text notes, datasets, and images. As part of the ongoing process of removing or simplifying extraneous parts of the code base, these should be sorted appropriately. These should be separated as documentation (to an appropriate `doc` top-level directory) or datasets (already separated to boost-starai/BoostSRL-Misc).

This issue will catalogue where the files exist, what the status of each are, whether they will be changed, and where they will be moved to.

---

# Known status of files

**Key:**

- [ ] Unresolved
- [X] Resolved

### Datasets:

**advisedby:**

- [x] `code/src/edu/wisc/cs/will/ILP/SampleTestbeds/advisedby/advisedby_bk.txt`
- [x] `code/src/edu/wisc/cs/will/ILP/SampleTestbeds/advisedby/advisedby_facts.txt`
- [x] `code/src/edu/wisc/cs/will/ILP/SampleTestbeds/advisedby/advisedby_neg.txt`
- [x] `code/src/edu/wisc/cs/will/ILP/SampleTestbeds/advisedby/advisedby_pos.txt`

**chess:**

- [x] `code/src/edu/wisc/cs/will/ILP/SampleTestbeds/chess/chess_bk.txt`
- [x] `code/src/edu/wisc/cs/will/ILP/SampleTestbeds/chess/chess_facts.txt`
- [x] `code/src/edu/wisc/cs/will/ILP/SampleTestbeds/chess/chess_neg.txt`
- [x] `code/src/edu/wisc/cs/will/ILP/SampleTestbeds/chess/chess_pos.txt`
- [x] `code/src/edu/wisc/cs/will/ILP/SampleTestbeds/chess/muggleChess_bk.txt`
- [x] `code/src/edu/wisc/cs/will/ILP/SampleTestbeds/chess/muggleChess_facts.txt`
- [x] `code/src/edu/wisc/cs/will/ILP/SampleTestbeds/chess/muggleChess_neg.txt`
- [x] `code/src/edu/wisc/cs/will/ILP/SampleTestbeds/chess/muggleChess_pos.txt`
- [x] `code/src/edu/wisc/cs/will/ILP/SampleTestbeds/chess/types.txt`

**ReadyToFly:**

- [x] `code/src/edu/wisc/cs/will/ILP/SampleTestbeds/ReadyToFly/ReadyToFly_allClauseAdvice.txt`
- [x] `code/src/edu/wisc/cs/will/ILP/SampleTestbeds/ReadyToFly/ReadyToFly_allFeatureAdvice.txt`
- [x] `code/src/edu/wisc/cs/will/ILP/SampleTestbeds/ReadyToFly/ReadyToFly_allSupplementalAdvice.txt`
- [x] `code/src/edu/wisc/cs/will/ILP/SampleTestbeds/ReadyToFly/ReadyToFly_bkRel.txt`
- [x] `code/src/edu/wisc/cs/will/ILP/SampleTestbeds/ReadyToFly/ReadyToFly_bk.txt`
- [x] `code/src/edu/wisc/cs/will/ILP/SampleTestbeds/ReadyToFly/ReadyToFly_facts.txt`
- [x] `code/src/edu/wisc/cs/will/ILP/SampleTestbeds/ReadyToFly/ReadyToFly_neg.txt`
- [x] `code/src/edu/wisc/cs/will/ILP/SampleTestbeds/ReadyToFly/ReadyToFly_pos.txt`

**Toy:**

- [x] `code/src/edu/wisc/cs/will/ILP/SampleTestbeds/toy/toy_bk.txt`
- [x] `code/src/edu/wisc/cs/will/ILP/SampleTestbeds/toy/toy_facts.txt`
- [x] `code/src/edu/wisc/cs/will/ILP/SampleTestbeds/toy/toy_neg.txt`
- [x] `code/src/edu/wisc/cs/will/ILP/SampleTestbeds/toy/toy_pos.txt`
- [x] `code/src/edu/wisc/cs/will/ILP/SampleTestbeds/toy/types.txt`

**Trains:**

- [x] `code/src/edu/wisc/cs/will/ILP/SampleTestbeds/trains/Trains_bk.txt`
- [x] `code/src/edu/wisc/cs/will/ILP/SampleTestbeds/trains/Trains_facts.txt`
- [x] `code/src/edu/wisc/cs/will/ILP/SampleTestbeds/trains/Trains_neg.txt`
- [x] `code/src/edu/wisc/cs/will/ILP/SampleTestbeds/trains/Trains_pos.txt`

**Upgrade:**

- [x] `code/src/edu/wisc/cs/will/ILP/SampleTestbeds/upgrade/upgrade_bk.txt`
- [x] `code/src/edu/wisc/cs/will/ILP/SampleTestbeds/upgrade/upgrade_facts.txt`
- [x] `code/src/edu/wisc/cs/will/ILP/SampleTestbeds/upgrade/upgrade_neg.txt`
- [x] `code/src/edu/wisc/cs/will/ILP/SampleTestbeds/upgrade/upgrade_pos.txt`

### Documentation

- [x] `code/src/edu/wisc/cs/will/ILP/willmanual/algorithmic.sty`
- [x] `code/src/edu/wisc/cs/will/ILP/willmanual/algorithm.sty`
- [x] `code/src/edu/wisc/cs/will/ILP/willmanual/README.txt`
- [x] `code/src/edu/wisc/cs/will/ILP/willmanual/will.bib`
- [x] `code/src/edu/wisc/cs/will/ILP/willmanual/will_definitions.tex`
- [x] `code/src/edu/wisc/cs/will/ILP/willmanual/will-manual.aux`
- [x] `code/src/edu/wisc/cs/will/ILP/willmanual/will-manual.bbl`
- [x] `code/src/edu/wisc/cs/will/ILP/willmanual/will-manual.blg`
- [x] `code/src/edu/wisc/cs/will/ILP/willmanual/will-manual.dvi`
- [x] `code/src/edu/wisc/cs/will/ILP/willmanual/will-manual.log`
- [x] `code/src/edu/wisc/cs/will/ILP/willmanual/will-manual.out`
- [x] `code/src/edu/wisc/cs/will/ILP/willmanual/will-manual.pdf`
- [x] `code/src/edu/wisc/cs/will/ILP/willmanual/will-manual.tcp`
- [x] `code/src/edu/wisc/cs/will/ILP/willmanual/will-manual.tex`
- [x] `code/src/edu/wisc/cs/will/ILP/willmanual/will-manual.toc`
- [x] `code/src/edu/wisc/cs/will/ILP/willmanual/will-manual.tps`

- [x] `code/src/edu/wisc/cs/will/ILP/willmanual/figs/new_run_configuration.png`
- [x] `code/src/edu/wisc/cs/will/ILP/willmanual/figs/open_run_configurations.png`
- [x] `code/src/edu/wisc/cs/will/ILP/willmanual/figs/run_configuration_arguments.png`
- [x] `code/src/edu/wisc/cs/will/ILP/willmanual/figs/run_configuration_ilpmain.png`

- [x] `code/src/edu/wisc/cs/will/ILP/willmanual/willmanualproject/willmanualproject.tcp`
- [x] `code/src/edu/wisc/cs/will/ILP/willmanual/willmanualproject/willmanualproject.tex`
- [x] `code/src/edu/wisc/cs/will/ILP/willmanual/willmanualproject/willmanualproject.tps`

### Unknown:

- [ ] `code/src/edu/wisc/cs/will/Boosting/RDN/RDNBoost Api Doc.docx`
- [x] `code/src/edu/wisc/cs/will/DataSetUtils/auc.jar`
- [ ] `code/src/edu/wisc/cs/will/FOPC_MLN_ILP_Parser/arithmeticInLogic.fopcLibrary`
- [ ] `code/src/edu/wisc/cs/will/FOPC_MLN_ILP_Parser/bootstrapBKinLogic.fopcLibrary`
- [ ] `code/src/edu/wisc/cs/will/FOPC_MLN_ILP_Parser/comparisonInLogic.fopcLibrary`
- [ ] `code/src/edu/wisc/cs/will/FOPC_MLN_ILP_Parser/differentInLogic.fopcLibrary`
- [ ] `code/src/edu/wisc/cs/will/FOPC_MLN_ILP_Parser/inlines_arithmeticInLogic.fopcLibrary`
- [ ] `code/src/edu/wisc/cs/will/FOPC_MLN_ILP_Parser/inlines_comparisonInLogic.fopcLibrary`
- [ ] `code/src/edu/wisc/cs/will/FOPC_MLN_ILP_Parser/inlines_differentInLogic.fopcLibrary`
- [ ] `code/src/edu/wisc/cs/will/FOPC_MLN_ILP_Parser/inlines_listsInLogic.fopcLibrary`
- [ ] `code/src/edu/wisc/cs/will/FOPC_MLN_ILP_Parser/listsInLogic.fopcLibrary`
- [ ] `code/src/edu/wisc/cs/will/FOPC_MLN_ILP_Parser/modes_advancedArithmeticInLogic.fopcLibrary`
- [ ] `code/src/edu/wisc/cs/will/FOPC_MLN_ILP_Parser/modes_advancedListsInLogic.fopcLibrary`
- [ ] `code/src/edu/wisc/cs/will/FOPC_MLN_ILP_Parser/modes_arithmeticInLogic.fopcLibrary`
- [ ] `code/src/edu/wisc/cs/will/FOPC_MLN_ILP_Parser/modes_comparisonInLogic.fopcLibrary`
- [ ] `code/src/edu/wisc/cs/will/FOPC_MLN_ILP_Parser/modes_differentInLogic.fopcLibrary`
- [ ] `code/src/edu/wisc/cs/will/FOPC_MLN_ILP_Parser/modes_listsInLogic.fopcLibrary`
- [ ] `code/src/edu/wisc/cs/will/FOPC_MLN_ILP_Parser/relevances_arithmeticInLogic.fopcLibrary`
- [ ] `code/src/edu/wisc/cs/will/FOPC_MLN_ILP_Parser/relevances_comparisonInLogic.fopcLibrary`
- [ ] `code/src/edu/wisc/cs/will/FOPC_MLN_ILP_Parser/relevances_differentInLogic.fopcLibrary`
- [ ] `code/src/edu/wisc/cs/will/FOPC_MLN_ILP_Parser/relevances_listsInLogic.fopcLibrary`
- [ ] `code/src/edu/wisc/cs/will/ILP/readmeCheckpointingAndCrossValidation.txt`

**Comment by batflyer** [comment]
Created a `docs/` directory and moved the WILL Manual into it.

**Comment by batflyer** [comment]
`Trains` domain is now present on https://github.com/boost-starai/BoostSRL-Misc/tree/master/Datasets/Trains/

**Comment by batflyer** [comment]
Two observations:

* `code/src/edu/wisc/cs/will/DataSetUtils/auc.jar` should not be altered, it is called somewhere in the code.

* Disk usage of the datasets amounts to ~29 MB. `ReadyToFly_facts.txt` is around 27 MB.

**Comment by batflyer** [comment]
Moved the SampleTestBeds into a directory called "ILP-Datasets" over in the BoostSRL-Misc repository. This seemed more appropriate since by default we expect a division between training and test sets.
https://github.com/boost-starai/BoostSRL-Misc/tree/master/ILP-Datasets
